### ISSUE TITLE
mybatis逆向的怎么开启啊，pom放开了，但是哪里开启啊

### ISSUE THREAD

**Issue by ayachaim** [impactCn/springBoot-scaffold#1]

**Comment by impactCn** [comment]
找到 resource 底下 generatorConfig.xml 配置好你的数据库。

然后再 pom 使用插件

**Comment by ayachaim** [comment]
不都是有個mybatis application启动的吗？generatorConfig和pom都装上了

**Comment by impactCn** [comment]
那个是插件，需要你自己去 application 配置。

**Comment by ayachaim** [comment]
接口文档里面加了吗，我加swagger2貌似切面返回无效token？

**Comment by impactCn** [comment]
没有 swagger. 返回无效 token 是因为没有 开放 接口。或者没有携带
